ifdef::env-github,env-gitea[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[[Top-of-the-page]]
= TestRail Migration to Klaros Test Management 
:toc: macro
:sectnums:

image:https://img.shields.io/badge/License-MIT-green[link="https://github.com/klaros-testmanagement/klaros-docker/blob/master/LICENSE"]
image:https://img.shields.io/badge/Community%20Edition-FREE-green[link="https://www.klaros-testmanagement.com/download"]
image:https://img.shields.io/twitter/follow/Klaros_TM?style=social[float="right", link="https://twitter.com/intent/follow?screen_name=Klaros_TM"]

toc::[]

== Introduction

This project offers software for importing test cases from https://www.testrail.com[TestRail]
XML export files to https://www.klaros-testmanagement.com/[Klaros Test Management].

=== About TestRail

TestRail is a web-based test management tool used by testers, developers and other stake holders
to manage, track and organize software testing efforts.

=== About Klaros Test Management

https://www.klaros-testmanagement.com/[Klaros Test Management] is a professional web-based test management software.
It contains components for resource management and evaluation of test activity.
Tracking of test requirements is supported, as well as agile development processes.
Numerous interfaces with issue trackers, test automation tools and continuous integration servers allow
seamless integration into existing development environments.

Klaros Test Management is available free of charge in the https://www.klaros-testmanagement.com/download[Community Edition] and can also be used for commercial purposes without restrictions.

The https://www.klaros-testmanagement.com/download[Enterprise Edition] offers you the full range of functions,
including one-year support and free access to all software updates.
An overview of the features of both editions can be found
https://www.klaros-testmanagement.com/test-management/test-management-tool-comparison[here].

To receive your free 30-day trial license for the Enterprise Edition, you can request your license key https://www.klaros-testmanagement.com/trial[here].

Detailed information, extensive <<Documentation,documentation>> and a freely accessible
https://www.klaros-testmanagement.com/demo/pages/login.seam[online demo]
can be found under https://www.klaros-testmanagement.com/home[Klaros Test Management].

== Exporting a TestRail XML File

Export your TestRail test specification to XML format as shown here: https://support.testrail.com/hc/en-us/articles/15144643126932-Export-test-cases#exporting-test-cases-to-xml-0-2[TestRail Support - Exporting test cases to XML]

== Importing a TestRail XML File

The import process consist of two steps:

. Transform the TestLink XML file to the Klaros import format using the provided Java archive file
. Upload the transformed file to the Klaros REST API

=== Transforming the TestRail XML File

The transformation process requires an installed Java 11 or better Runtime Environment (JRE) and a current release of this software.

In the command line execution example below the following placeholder are present:

<TESTRAIL_XML>: The path to the TestRail XML file to import
<KLAROS_XML>: The path to the Klaros XML import file to convert these test cases to

[source, bash]
----
java -Xmx512m -jar testrail-migration-1.0.0.jar -t <TESTRAIL_XML> -T <KLAROS_XML>
----

=== Uploading the Transformed XML File

For uploading the result file to Klaros you may use the command line tool https://curl.se/[Curl] which
is available as a package under Linux or Cygwin for Windows.

Of course, using https://www.gnu.org/software/wget/[GNU wget] or any other tool for sending HTTP requests
is possible here as well.

[source, bash]
----
curl -v -T klaros-testcases.xml "http://localhost:18080/klaros-web/seam/resource/rest/import/testcase/xml?config=P0000X&username=admin&password=admin"
----

Please substitute 'P0000X' wwith the project id of the project you want to import to.
Likewise make sure to add the correct credentials in the username/password attributes.
The credentials must identify a user with role `Testmanager` for the above project. 

The import interface is described in detail in the
https://www.klaros-testmanagement.com/files/doc/html/User-Manual.Import-Export.html#User-Manual.Import-Export.Import-Testcases-From-XML[Klaros User Manual, Section "Importing Test Cases from XML"] 

=== Test Case Sections

If your TestRail test cases are using sections, this information will be automatically be mapped to Klaros test case categories upon import.
This requires the Enterprise Edition, as categories are only available there.

=== Scope and Limitations

This migration is able to transfer mostly all of the test case information, including test step descriptions and expected results.

Test case attachments will currently not be transferred.
